name: 'action-package-version-to-git-tag'
description: 'npm publish & push git tag to repository if the version is not published.'
author: 'azu'
inputs:
  version:
    description: 'define version explicitly. if it is not defined, use package.json version'
    required: false
  github_token:
    description: 'GITHUB_TOKEN'
    required: true
  git_commit_sha:
    description: 'Git commit SHA'
    required: true
  git_tag_prefix:
    description: "prefix for git tag. Example) 'v'"
    required: false
    default: ""
  github_repo:
    description: 'GitHub repository path. Example) azu/test'
    required: true
runs:
  using: 'node12'
  main: 'lib/main.js'
branding:
  icon: 'alert-octagon'
  color: 'blue'
